# Generated by Django 4.0.8 on 2023-01-26 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='duration',
        ),
    ]
